Repository DevCourse-project-2/BikeTracer-FrontEnd, pull requests merged in 2024-08, with the labels that each got.

#2 chore: 기본 디자인 시스템 구현
  src/assets/fonts/PretendardVariable.woff2
  src/index.css
  src/styles/color.ts
  src/styles/typo.ts
Labels: chore

#4 feat: 기본 레이아웃 설정
  .eslintrc.json
  index.html
  public/manifest.json
  src/App.css
  src/App.tsx
  src/index.css
  src/layout/layout.tsx
  src/main.tsx
  src/pages/AlarmPage/AlarmPage.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/MainPage/MainPage.tsx
  tsconfig.app.json
Labels: chore, feature

#5 Feat/layout main page
  index.html
  public/Vector-basic.png
  public/Vector-select.png
  public/menu.png
  public/notification.png
  public/sparkling-fill.png
  src/App.tsx
  src/component/atoms/batteryStatus/batteryStatus.styled.ts
  src/component/atoms/batteryStatus/batteryStatus.tsx
  src/component/atoms/bicycleInfo/bicycleInfo.styled.ts
  src/component/atoms/bicycleInfo/bicycleInfo.tsx
  src/component/atoms/joinButton/joinButton.style.ts
  src/component/atoms/joinButton/joinButton.tsx
  src/component/atoms/loginButton/loginButton.style.ts
  src/component/atoms/loginButton/loginButton.tsx
  src/component/atoms/mapBox/mapBox.tsx
  src/component/atoms/registerButton/registerButton.style.ts
  src/component/atoms/registerButton/registerButton.tsx
  src/component/atoms/registerCancleButton/registerCancleButton.style.ts
  src/component/atoms/registerCancleButton/registerCancleButton.tsx
  src/component/molecules/isLoginInfo/isLoginInfo.style.ts
  src/component/molecules/isLoginInfo/isLoginInfo.tsx
  src/component/molecules/mainScreen/mainScreen.style.ts
  src/component/molecules/mainScreen/mainScreen.tsx
  src/component/molecules/searchBar/searchBar.style.ts
  src/component/molecules/searchBar/searchBar.tsx
  src/component/molecules/stationInfo/stationInfo.style.ts
  src/component/molecules/stationInfo/stationInfo.tsx
  src/pages/MainPage/MainPage.tsx
  src/styles/typo.ts
  src/types/types.ts
  src/utils/getColor.ts
Labels: feature, markup, pull requests
